apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backstage-teste
  annotations:
    github.com/project-slug: Darckfast/backstage-teste
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: experimental
  owner: guests
  system: examples
  definition: 
    $text: https://petstore.swagger.io/v2/swagger.json