apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-grpc-api
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: experimental
  owner: guests
  system: examples
  definition: 
    $json: https://petstore.swagger.io/v2/swagger.json